version: '3.8'
networks:
    lysori-net:
      driver: bridge
      name: lysori-net

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html/
    ports:
      - "8099:80"
    networks:
      - lysori-net
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
  
  fluentd:
    build: ./fluentd
    volumes:
     - ./fluentd/conf:/fluentd/etc
    depends_on:
     - "elasticsearch"
    ports:
     - "24224:24224"
     - "24224:24224/udp"
    networks:
     - lysori-net

  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports: 
      - "9200:9200"
    networks:
      - lysori-net
     
  kibana:
    image: kibana:7.9.2
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - lysori-net
